
@baseUrl = http://localhost:3000

### 1. 上传测试
POST {{baseUrl}}/material/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="subject"

数据结构
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="data_structure.pdf"
Content-Type: application/pdf

< ./test.pdf
--WebAppBoundary--


---

### 2. 语义搜索测试
GET {{baseUrl}}/material/search?queryText=已知一个树结构每个节点最多有两个孩子求总节点数&subject=数据结构

---

GET {{baseUrl}}/material/search?queryText=什么是递归算法的执行效率

### OCR测试
### 3. 识图搜题测试 (OCR + 语义搜索)
# 注意：确保当前目录下有一个名为 question.jpg 的真实图片
POST {{baseUrl}}/material/ocr-search
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="subject"

数据结构
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/jpeg

< ./test.jpg
--WebAppBoundary--